### ISSUE TITLE
작픔 상세페이지 반응형 구현

### ISSUE THREAD

**Issue by minzziPark** [2024-hgu-ccd-one-in-christ/hgu-one-in-christ#50]
## 이슈 상세
- 작품상세페이지 반응형 구현

## TODO

- [x] 개인 작품 반응형
- [x] 단체 작품 반응형
- [x] 디자이너 부분 반응형
- [x] 컨텐츠 부분 반응형
